org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true
org.gradle.configuration-cache=false

mod.id=enchantmentdisabler
mod.name=Enchantment Disabler
mod.group=me.pajic
mod.version=3.4.4
mod.channel_tag=
mod.authors=pajic
mod.contributors=
mod.license=MIT
mod.description=Disable enchantments and nerf enchanting in multiple ways with an extensive configuration
mod.sources_url=https://github.com/pajicadvance/enchantmentdisabler
mod.homepage_url=https://modrinth.com/mod/enchantment-disabler
mod.issues_url=https://github.com/pajicadvance/enchantmentdisabler/issues
mod.discord_url=https://discord.gg/5RkzS66zWb

deps.minecraft=[VERSIONED]
deps.parchment=[VERSIONED]
deps.fabric-api=[VERSIONED]
deps.neoforge=[VERSIONED]
deps.mixson=[VERSIONED]
deps.modmenu=[VERSIONED]
deps.fzzy_config=[VERSIONED]

deps.emi=[VERSIONED]
deps.rei=[VERSIONED]
deps.jei=[VERSIONED]
deps.rrv=[VERSIONED]

publish.modrinth=Kd03i2oU
publish.curseforge=912326
publish.github=false
