# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
# Fabric Properties
# check these on https://modmuss50.me/fabric.html
loader_version=0.16.13
parchment_version=[VERSIONED]
# Mod Properties
mod_version=3.2.3
maven_group=me.pajic
archives_base_name=enchantmentdisabler
# Dependencies
# check this on https://modmuss50.me/fabric.html
fabric_version=[VERSIONED]
mixinextras_version=0.5.0-rc.2
mixson_version=v1.3.1.1
modmenu_version=[VERSIONED]
owo_version=[VERSIONED]

emi_version=[VERSIONED]
rei_version=[VERSIONED]