license = "${license}"
modLoader="javafml"
loaderVersion="[1,)"

[[mods]]
modId = "${id}"
displayName = "${name}"
version = "${version}"
authors = "${authors}"
credits = "${contributors}"
description = "${description}"
logoFile = "icon.png"
displayURL = "${homepage_url}"
issueTrackerURL = "${issues_url}"

[[mixins]]
config = "${id}.mixins.json"

${dependencies}
