# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G

# Fabric Properties
	# check these on https://modmuss50.me/fabric.html
	minecraft_version=1.19
	loader_version=0.15.11
	parchment_version=1.19.2:2022.11.27

# Mod Properties
	mod_version = 1.0.0
	maven_group = me.pajic
	archives_base_name = enchantmentdisabler

# Dependencies
	# check this on https://modmuss50.me/fabric.html
	fabric_version=0.58.0+1.19
	modmenu_version=4.0.4
	owo_version=0.9.3+1.19