# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G

# Fabric Properties
minecraft_version=1.21.1
loader_version=0.16.2
parchment_version=1.21:2024.07.28

# Mod Properties
mod_version = 2.3.3
maven_group = me.pajic
archives_base_name = enchantmentdisabler

# Dependenciess
fabric_version=0.102.1+1.21.1
mixinextras_version=0.5.0-beta.2
jsonpatcher_version=1.1.0-mc.1.21.1
modmenu_version=11.0.1
owo_version=0.12.11+1.21
emi_version=1.1.12+1.21